### ISSUE TITLE
[Bug] npm run start is not working

### ISSUE THREAD

**Issue by newbeelearn** [4044ever/Hugo-Tailwind-4.x#3]
I am getting following error when trying to execute "npm run start" command. I have not made any changes just cloned the site and executed this command after installation. Any idea what is going wrong? I am able to run both watch commands separately without any issue

Env Details:
OS:ubuntu 20.0
node: v16.15.1
npm: 6.14.7

Error Message:

> hugotw3@1.0.0 start /media/lenovo/Windows/linuxdocs/workspace/projects/newbeelearn.com/tailwind-hugo-theme/Hugo-Tailwind-3.0
> concurrently npm:watch:*

[watch:*tw] npm run watch:tw exited with code 243
[watch:*hugo] npm run watch:hugo exited with code 243
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hugotw3@1.0.0 start: `concurrently npm:watch:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hugotw3@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by 4044ever** [comment]
Added, but should come first:  For unknown reason it can happen that an error is thrown the first time you do `npm run start` - so just run it again. Usually it's fine then. If not.....

-----------------------------------

Do you have Hugo installed and running correctly? 

Try in terminal:` hugo version`
And you should get something like:

hugo v0.100.2-d25cb2943fd94ecf781412aeff9682d5dc62e284+extended windows/amd64 BuildDate=2022-06-08T10:25:57Z VendorInfo=gohugoio

Next, did you run `npm install` ?

Also try the `hugo server` directly. You should see the project at `localhost:1313`, Tailwind changes may not work though.This said, I will do update soon for

**Comment by newbeelearn** [comment]
Yes hugo is installed and i am able to run "npm run watch:tw" and "npm run watch:hugo". 
I can see the page with "This is 6xl in Cyan" with "npm run watch:hugo" so it doesn't looks like hugo issue.

**Comment by 4044ever** [comment]
Great it worked!

**Comment by newbeelearn** [comment]
It is not working with "npm run start" so that needs to be debugged however i am unblocked by using "yarn run start".
